### ISSUE TITLE
TODO Changes

### ISSUE THREAD

**Issue by chriselrod** [LoopOptimization/Math#2]
- [ ] `TinyVector` -> `TinyArray`, `Vector` referring to mathematical objects that have `ExprTemplate` support.
- [ ] `**Matrix` -> `*Strided*Matrix` and `*Dense*Matrix` -> `**Matrix`, so `Dense` becomes the default.
- [ ] `BitSet` parameterized by bit amounts.
- [ ] `int64_t` -> `using i64 = signed long long int`, in part because `immintrin.h` assumes this.
- [ ] Implementation files for better compile times, in particular for linear algebra and Simplex.
- [ ] Add option to turn on optimizations for debug-mode, with selective `#pragma`s to turn it off parts more likely to be interesting to debugging. Some optimized regions could exclude debug info for GCC's sake to improve compile times. The idea here is that `Expr` template code in particular should be made lighter. When doing this, we should also `extern` some templates identified by clang tracing to be the most expensive instantiations.
- [ ] `Tuple` fields to `_0`, `_1`, etc.
- [ ] `template <F,S> using Pair = Tuple<F,S>`
- [ ] `std::print` and `std::format` instead of `iostream`
